@startuml

package mud_core {
    players "1" *-- "1" equipments : equipment_id
    players "1" *-- "1" location_items : current_location_id
    players "1" *-- "1" location_items : past_location_id
    players "1" *-- "many" player_params : params_collection_id
    equipments "1" *-- "many" item_lists : backpack_id
    location_items "1" *-- "many" item_lists : item_list_id
    location_items "1" *-- "many" item_lists : static_item_list_id
}

package mud_db_interface {
    player_commands "many" *-- "1" players : player_id
    processed_player_response "many" *-- "1" player_commands : command_id
    processed_player_response "many" *-- "1" players : player_id
}

class location_items {
    String location_id
    String item_list_id
    String static_item_list_id
}

class item_lists {
    String owner_id
    String list_id
    String item_id
    String item_name
    int amount
}

class equipments {
    Armor head_item_id
    Armor torso_item_id
    Armor hands_item_id
    Armor legs_item_id
    Armor feet_item_id
    
    Weapon melee_weapon_id
    Weapon range_weapon_id
    
    String backpack_id
}

class players {
    String name

    Integer strength
    Integer dexterity
    Integer endurance
    Integer intelligence
    Integer wisdom
    Integer charisma
    
    String equipment_id

    String current_location_id;
    String past_location_id;

    long last_activity_timestamp

    String params_collection_id
}

class player_params {
    String player_id
    String key
    String value
}

class processed_player_response {
    String id
    String player_id
    String player_nick
    String response
    String command_id
    boolean sent
}

class player_commands {
    String id;
    String player_id;
    String player_nick;
    String command;
    boolean processed;
    long timestamp;
}

@enduml
